# Generated by Django 3.1.1 on 2020-09-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20200928_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='imposto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
