# Generated by Django 3.1.1 on 2020-09-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20200929_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendas',
            options={'permissions': (('setar_nfe', 'Usuario pode alterar parametro NF-e'), ('permissao2', 'permissao2'), ('permissao3', 'permissao3'))},
        ),
    ]
